version: '3.8'

services:
  app:
    container_name: nestjs_app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RUNNING_IN_DOCKER=true
  db:
    container_name: postgres_db
    image: postgres:13
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: track_e_trace_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:7.0.8-alpine

volumes:
  postgres_data:
